@startuml

legend top center
Treadmill 2.1 Communication WP3 Serial Protocol
end legend

participant "Supervisor" as SUPERVISOR
participant "Gamenastix Driver" as DRIVER

SUPERVISOR -> DRIVER: Frame (F)
SUPERVISOR -> DRIVER: Frame (F)
...
DRIVER -> SUPERVISOR: RequestModel (R)
SUPERVISOR -> DRIVER: ResponseModel (M)
...
DRIVER -> SUPERVISOR: BumpFrameRate (B)
...
SUPERVISOR -> DRIVER: Frame (F)
SUPERVISOR -> DRIVER: Frame (F)
...
DRIVER -> SUPERVISOR: CalibrationNPose (N)
DRIVER -> SUPERVISOR: CalibrationSPose (S)
...
SUPERVISOR -> DRIVER: Frame (F)
SUPERVISOR -> DRIVER: Frame (F)

@enduml